/* database initialization data */
USE dssm;

INSERT INTO ssm_admin(id, login_name, password, real_name, email, mobile, create_aid, create_time, remark) VALUES
(1, 'administrator', '123456', '超级管理员', 'xishizhang@gmail.com', '15121191401', 1, NOW(), '系统初始化数据');

INSERT INTO ssm_role(id, name, code, description) VALUES
(1, '超级管理员', 'administrator', '系统初始化数据'),
(2, '日志管理员', 'log:manager', '系统初始化数据'),
(3, '缓存管理员', 'cache:manager', '系统初始化数据');

INSERT INTO ssm_relate_admin_role(admin_id, role_id) VALUES(1, 1);

INSERT INTO ssm_permission(name, code, description) VALUES
('查看权限', 'permission:show', '系统初始化数据'),
('添加权限', 'permission:new', '系统初始化数据'),
('编辑权限', 'permission:edit', '系统初始化数据'),
('删除权限', 'permission:remove', '系统初始化数据'),
('查看角色', 'role:show', '系统初始化数据'),
('添加角色', 'role:new', '系统初始化数据'),
('编辑角色', 'role:edit', '系统初始化数据'),
('删除角色', 'role:remove', '系统初始化数据'),
('分配权限', 'role:authorize', '系统初始化数据'),
('查看管理员', 'admin:show', '系统初始化数据'),
('添加管理员', 'admin:new', '系统初始化数据'),
('编辑管理员', 'admin:edit', '系统初始化数据'),
('删除管理员', 'admin:remove', '系统初始化数据'),
('分配角色', 'admin:authorize', '系统初始化数据'),
('查看菜单', 'menu:show', '系统初始化数据'),
('添加菜单', 'menu:new', '系统初始化数据'),
('编辑菜单', 'menu:edit', '系统初始化数据'),
('删除菜单', 'menu:remove', '系统初始化数据'),
('查看供应商', 'provider:show', '系统初始化数据'),
('添加供应商', 'provider:new', '系统初始化数据'),
('编辑供应商', 'provider:edit', '系统初始化数据'),
('删除供应商', 'provider:remove', '系统初始化数据'),
('查看分类', 'category:show', '系统初始化数据'),
('添加分类', 'category:new', '系统初始化数据'),
('编辑分类', 'category:edit', '系统初始化数据'),
('删除分类', 'category:remove', '系统初始化数据'),
('查看品牌', 'brand:show', '系统初始化数据'),
('添加品牌', 'brand:new', '系统初始化数据'),
('编辑品牌', 'brand:edit', '系统初始化数据'),
('删除品牌', 'brand:remove', '系统初始化数据'),
('查看颜色', 'color:show', '系统初始化数据'),
('添加颜色', 'color:new', '系统初始化数据'),
('编辑颜色', 'color:edit', '系统初始化数据'),
('删除颜色', 'color:remove', '系统初始化数据'),
('查看尺寸', 'size:show', '系统初始化数据'),
('添加尺寸', 'size:new', '系统初始化数据'),
('编辑尺寸', 'size:edit', '系统初始化数据'),
('删除尺寸', 'size:remove', '系统初始化数据'),
('查看批次', 'batch:show', '系统初始化数据'),
('添加批次', 'batch:new', '系统初始化数据'),
('编辑批次', 'batch:edit', '系统初始化数据'),
('删除批次', 'batch:remove', '系统初始化数据'),
('查看事务类型', 'transtype:show', '系统初始化数据'),
('添加事务类型', 'transtype:new', '系统初始化数据'),
('编辑事务类型', 'transtype:edit', '系统初始化数据'),
('删除事务类型', 'transtype:remove', '系统初始化数据'),
('查看仓库', 'depot:show', '系统初始化数据'),
('添加仓库', 'depot:new', '系统初始化数据'),
('编辑仓库', 'depot:edit', '系统初始化数据'),
('删除仓库', 'depot:remove', '系统初始化数据'),
('查看平台', 'platform:show', '系统初始化数据'),
('添加平台', 'platform:new', '系统初始化数据'),
('编辑平台', 'platform:edit', '系统初始化数据'),
('删除平台', 'platform:remove', '系统初始化数据'),
('查看网店', 'shop:show', '系统初始化数据'),
('添加网店', 'shop:new', '系统初始化数据'),
('编辑网店', 'shop:edit', '系统初始化数据'),
('删除网店', 'shop:remove', '系统初始化数据');

INSERT INTO ssm_menu(parent_id, name, code, link, sequence, update_aid, update_time) VALUES
(0, '系统管理', 'system', null, 99, 1, NOW()),
(0, '基础设置', 'setting', null, 95, 1, NOW()),
(0, '商品管理', 'product', null, 85, 1, NOW()),
(0, '仓储管理', 'warehouse', null, 80, 1, NOW()),
(0, '订单管理', 'order', null, 75, 1, NOW()),
(1, '管理员管理', 'admin', '/admin', 9, 1, NOW()),
(1, '角色管理', 'role', '/role', 8, 1, NOW()),
(1, '权限管理', 'permission', '/permission', 7, 1, NOW()),
(1, '缓存管理', 'cache', '/cache', 6, 1, NOW()),
(1, '日志管理', 'log', '/log', 5, 1, NOW()),
(2, '菜单设置', 'menu', '/menu', 9, 1, NOW()),
(2, '平台设置', 'platform', '/platform', 8, 1, NOW()),
(2, '网店设置', 'shop', '/shop', 7, 1, NOW()),
(2, '仓库设置', 'depot', '/depot', 6, 1, NOW()),
(2, '物流设置', 'shipping', '/shipping', 5, 1, NOW()),
(3, '供应商管理', 'provider', '/provider', 9, 1, NOW()),
(3, '分类管理', 'category', '/category', 8, 1, NOW()),
(3, '品牌管理', 'brand', '/brand', 7, 1, NOW()),
(3, '颜色管理', 'color', '/color', 6, 1, NOW()),
(3, '尺寸管理', 'size', '/size', 5, 1, NOW()),
(3, '批次管理', 'batch', '/batch', 4, 1, NOW()),
(4, '事务类型管理', 'transtype', '/transtype', 9, 1, NOW());